theme = "sonokai-white-cursor"

[editor]
line-number = "relative"
mouse = true
end-of-line-diagnostics = "hint"
cursorline = true
rulers = [80, 100]
bufferline = "never"
scrolloff = 0

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[editor.whitespace.characters]
tab = "→"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1

[keys.normal]
C-e = ["scroll_down", "scroll_down"]
C-y = ["scroll_up", "scroll_up"]
A-space = ":wa"
